name: "Deploy to GKE"
on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'

env:
  PROJECT_ID: nestjs
  GAR_LOCATION: australia-southeast1
  REPOSITORY: nestjs
  IMAGE: nestjs-backend

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        mongodb-version: [ '6.0' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:cov


  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Docker build'
        run: |-
          docker build -t "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest" .

# push to gcr
#      - id: 'auth'
#        name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v1'
#        with:
#          credentials_json: '${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }}'
#
#      - name: 'Docker push'
#        run: |-
#          gcloud auth configure-docker $GAR_LOCATION-docker.pkg.dev
#          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest"

